### ISSUE TITLE
__product__options__tab__ mit Fehlern

### ISSUE THREAD

**Issue by webregie** [Blur-Creative/theme-views#79]
### Report

Ich habe über das Shopware Backend das letzte Update geladen. Beim Generieren der Templates brach es mit einem Fehler ab. 
Wenn ich den Haken bei __product_box_advanced_badges_options__ entferne, kann das Template generiert werden. 
Alle Beschriftungen des Reiters und im Reiter fehlen.

**Comment by Blur-Creative** [comment]
wie lautete der Kompilierungs-Fehler?

**Comment by webregie** [comment]
Na doll. Jetzt hatte ich es deaktiviert und kompiliert. dann alleine aktiviert und kompiliert - das funktionierte. Dann alles wieder aktiviert. Ohne Fehler. Sehr merkwürdig.

**Comment by Blur-Creative** [comment]
Kann sein dass das Theme die neu hinzugekommene LESS Variable noch nicht kannte. Am besten im Theme Manager das Theme neu laden und direkt nach dem Update erstmal kompilieren.

Zu den fehlenden Textbausteinen gibt es hier eine Anleitung:
https://blur-creative.github.io/theme-views/de/troubleshooting

**Comment by webregie** [comment]
Wie schön, dass sich alles lösen lässt. Sehr gut programmiert. Danke.

**Comment by Blur-Creative** [comment]
Danke auch für den Fehler Report.
Wurde in die Dokumentation mit aufgenommen https://blur-creative.github.io/theme-views/de/troubleshooting
