### ISSUE TITLE
Register page - country states not provided at the first time

### ISSUE THREAD

**Issue by talheim-it** [Blur-Creative/theme-views#84]
### Report

If you want to register at the first time and if the shop has states active to choose, they are not shown of the country.

### Possible Solution

At the moment I fixed it myself by removing the .tpl for billing and shipping address.

**Comment by Blur-Creative** [comment]
should be fixed in commit [b92465d](https://github.com/Blur-Creative/theme-views/commit/b92465d2b917e52c0e98445dfd4e4aa8481a8fbf)

**Comment by webregie** [comment]
Ich habe jetzt bei Zurück einen Oberkörper und bei Weiter einen Schlüssel. Muss ich da was tun?

**Comment by talheim-it** [comment]
@webregie was genau meinst du? Screenshot?

**Comment by webregie** [comment]
![2018 08 07_02_sceenshot](https://user-images.githubusercontent.com/3647431/43796587-f4bdafbc-9a84-11e8-9d68-64aa38360bdc.jpg)

**Comment by talheim-it** [comment]
Hallo @webregie ,
schickst du mir eine Url, gerne auch an meine E-Mail mathias.rumbold@talheim-it.at, dann seh ich mir das direkt auf der Seite an.

**Comment by Blur-Creative** [comment]
In der Version 1.3.2 gibt es wohl ein Problem mit dem Icon Mapping.
Habe ein neues Ticket dafür eröffnet #88

Bis das Problem gefixt ist empfehle ich auf die Version 1.3.1 zurück zu spielen

**Comment by webregie** [comment]
Wahrscheinlich findest du das Problem wieder pfeilschnell, sodass ich keine Versionen zurückspielen muss ;)
