### ISSUE TITLE
Article - SEO-URL by varieties not generated correctly, order-id is missing in url

### ISSUE THREAD

**Issue by talheim-it** [Blur-Creative/theme-views#87]
Issue:
When you have a variation article, the seo-url is not generated correctly.

Example: => https://webstore.talheim-records.at/de/buendel/deadspace/happy-days-reaching-for-silence-cd-t-shirt-maenner/

When you want to switch to another size => https://webstore.talheim-records.at/de/buendel/deadspace/happy-days-reaching-for-silence-cd-t-shirt-maenner/?number=

After ?number= the variety id of the article should be generated.

That is not happening. Also tested with blank views theme.

**Comment by talheim-it** [comment]
@Blur-Creative is there a status for this issue?

**Comment by Blur-Creative** [comment]
fixed in commit https://github.com/Blur-Creative/theme-views/commit/6ab3a96046428ce6c0ae24b93c136f85aa3fffb7
