### ISSUE TITLE
Shopware 5.5.1 - Footer-Navigation.tpl - Service & Information Links breaking

### ISSUE THREAD

**Issue by talheim-it** [Blur-Creative/theme-views#90]
Hello,

es hat sich in der Footer-Navigation.tpl etwas geändert aufgrund der Anpassungen der Links, dass diese nun übersetzbar sind.

Nach dem Update auf 5.5.1 tritt die Situation auf. Dafür müssen die Blöcke von Information und Service angepasst werden.

**Comment by Blur-Creative** [comment]
Ist in dem commit https://github.com/Blur-Creative/theme-views/commit/2ad2452a274c69804a27a19f86d994ad01c17532 gefixt. Kommt dann in Version 1.3.5
