### ISSUE TITLE
Scroll-to-top Button - Bei Erscheinung wird der Header mit neugeladen

### ISSUE THREAD

**Issue by talheim-it** [Blur-Creative/theme-views#93]
Beim Anpassen des Themes ist mir aufgefallen, dass sobald der Scroll-To-Top Button beim runterscrollen erscheint, der Header, Header-Navigation quasi dazugeladen wird. Das sollte nicht sein.

Das hat zu Folge, dass in der mobilen Version der Header auf einmal in der Mitte erscheint mit Abstand nach oben. Sieht merkwürdig aus.

Vl. kann man an der Nachladeoption etwas verbessern? Option B. wäre, dass man das Scroll-To-Top permanent anzeigt, dann wird es nicht erst beim scrollen nachgeladen.

@Blur-Creative - Könnt ihr das verifizieren oder braucht ihr dazu noch etwas?

LG,
Mathias

**Comment by webregie** [comment]
Das ist mir auch aufgefallen. Die Seite springt irgendwie nach 128px in der mobilen Version... www.gokarthof.de

**Comment by Blur-Creative** [comment]
Tritt das Verhalten nur Mobil oder auch auf dem Desktop auf?

**Comment by talheim-it** [comment]
Tritt nur mobil auf.

**Comment by Blur-Creative** [comment]
Ist folgendes aktiviert?
- Sticky Header
- Vorteilsbalken

**Comment by talheim-it** [comment]
Sticky Header ja. Müsste in der mobile Versionen dann quasi ausgenommen werden?

**Comment by Blur-Creative** [comment]
Ja, die sticky navigation sollte nur im tablet, tablet landscape und desktop aktiviert sein.
ist jetzt in diesem commit f23fd4d7860ce6e5013c142c058f78ccce20e6fa angepasst.
Das sollte den Scroll-to-Top Bug beheben.

Bitte das Issue wieder öffnen falls es doch noch Probleme gibt.
