### ISSUE TITLE
Badges werden dauerhaft eingeblendet

### ISSUE THREAD

**Issue by lrzcgn** [Blur-Creative/theme-views#94]
Hi !

Habe das Problem, dass das Badge TIPP dauerhaft angezeigt wird, obwohl ich es im Backend deaktiviert habe. Im Artikel ist kein Haken bei hervorheben gesetzt.. Gibt es da noch eine andere Methode oder ist es evtl. ein bug ? Nutze Shopware 5.5.1 und die aktuellste Version des Views Theme..

LG ;)

**Comment by talheim-it** [comment]
Das ist hardcoded im detail Verzeichnis.

Dort die entsprechende datei anpassen. 

Ich schreib einen pull Request dazu.

LG,
Mathias

**Comment by Blur-Creative** [comment]
In COmit 55e1d066a0541db89d5855c1b2c85c7dd992d05e gefixed
