### ISSUE TITLE
paypal Problem SW 5.5.3

### ISSUE THREAD

**Issue by leseaw** [Blur-Creative/theme-views#96]
### Report

Es ist nicht möglich die Detailseite einen Artikels aufzurufen, erscheint sofort Fehler.
`SmartyCompilerException: Syntax Error in template /custom/plugins/BlurThemeViews/Resources/Themes/Frontend/Views/frontend/paypal_unified/express_checkout/button_detail.tpl&quot;  on line 2 &quot;&quot; illegal recursive call of &quot;parent:frontend/paypal_unified/express_checkout/button_detail.tpl&quot; in /engine/Library/Smarty/sysplugins/smarty_internal_templatecompilerbase.php:657 Stack trace:`

Falls ihr mehr Logs braucht sagt Bescheid.
SW 5.5.3 PHP7 Debian

### Possible Solution

Original Template nehmen von Shopware5, damit geht es. Sieht nur nicht so gut aus :(

**Comment by Blur-Creative** [comment]
Danke für den Hinweis.
Ich nehme an PayPal wird nicht in dem Shop verwndet?

**Comment by leseaw** [comment]
War nur installiert aber noch nicht eingerichtet :)
Habe jetzt die Datei button_detail.tpl mit __ auskommentiert so das ich weiter komme.
